### ISSUE TITLE
hemera test fails for async/await

### ISSUE THREAD

**Issue by veeramarni** [hemerajs/hemera-testsuite#5]
_Versions_
hemera-testsuite: 1.2.0
Node: 8.4.0
npm: 5.2 v
nats-hemera: 1.5.13

`Sample example`
```
'use strict';

const Hp = require('hemera-plugin');

exports.plugin = Hp(function hemeraTestPlugin(options, next) {
    const hemera = this;
    const topic = 'testPlugin';
    this.log.info('received options (%j)', options);
    hemera.add({
        topic,
        cmd: 'add',
    }, async function (req) {
        const result = await Promise.resolve({
            result: req.a + req.b,
        });
        return result;
    });

    next();
});

exports.options = {};

exports.attributes = {
    pkg: require('../../package.json'),
};

```
`test case`
```
'use strict';

const Hemera = require('nats-hemera');
const Plugin1 = require('./example-async');
const HemeraTestsuite = require('hemera-testsuite');


// prevent warning message of too much listeners
process.setMaxListeners(0);

describe('hemera-testPlugin', function () {
    const PORT = 4222;
    const topic = 'testPlugin';
    let server;

    // Start up our own nats-server
    beforeAll(function (done) {
        server = HemeraTestsuite.start_server(PORT, done);
    });

    // Shutdown our server after we are done
    afterAll(function (done) {
        server.kill();
        done();
    });

    it('Should be able to add two numbers', function (done) {
        const nats = require('nats').connect();
        const options = { a: 1 };
        const hemera = new Hemera(nats, {
            logLevel: 'info',
        });
        hemera.use(Plugin1, options);

        hemera.ready(() => {
            hemera.ext('onServerPreRequest', async function (ctx, req, res) {
                await Promise.resolve();
            });

            hemera.act({
                topic,
                cmd: 'add',
                a: 1,
                b: 20,
            }, async function (err, resp) {
                try {
                    await resp;
                    expect(err).toBeNull();
                    expect(resp.result).toEqual(21);
                    hemera.close(done);
                } catch (err) {
                    hemera.close(done.fail);
                }

            });
        });

    });
});
```

**Comment by StarpTech** [comment]
@veeramarni thanks for report. Async / Await is only supported with NodeJs 7.6+

**Comment by StarpTech** [comment]
Hi @veeramarni  What's the error log?

**Comment by veeramarni** [comment]
'error.log`
```

[2017-09-15T15:08:28.599Z] INFO (hemera-Veeras-MacBook-Pro.local-4c45357652a74231a2b8874d9ee670aa/94571 on Veera
s-MacBook-Pro.local): @xterm-stack/hemera-plugin PLUGIN - ADDED!
[2017-09-15T15:08:28.605Z] INFO (hemera-Veeras-MacBook-Pro.local-4c45357652a74231a2b8874d9ee670aa/94571 on Veeras-MacBook-Pro.local): Connected!
[2017-09-15T15:08:28.606Z] INFO (hemera-Veeras-MacBook-Pro.local-4c45357652a74231a2b8874d9ee670aa/94571 on Veeras-MacBook-Pro.local): received options ({"a":1})
[2017-09-15T15:08:28.608Z] INFO (hemera-Veeras-MacBook-Pro.local-4c45357652a74231a2b8874d9ee670aa/94571 on Veeras-MacBook-Pro.local): ADD - ADDED
    topic: "testPlugin"
    cmd: "add"
[2017-09-15T15:08:30.618Z] ERROR (hemera-Veeras-MacBook-Pro.local-4c45357652a74231a2b8874d9ee670aa/94571 on Veer
as-MacBook-Pro.local): Timeout
    TimeoutError
        at timeoutHandler (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/xterm-stack/node_modules/nats-hemera/lib/index.js:1037:21)
        at Timeout._onTimeout (/Users/veeramarni/Documents/eclipse/workspace/phoneapps/development/projects/IDE/xterm-stack/node_modules/nats/lib/nats.js:1242:5)
        at ontimeout (timers.js:469:11)
        at tryOnTimeout (timers.js:304:5)
        at Timer.listOnTimeout (timers.js:264:5)
 FAIL  src/__tests__/example-async.test.ts (5.512s)
  ● hemera-testPlugin › Should be able to add two numbers

    Failed

      at stackFormatter (../../node_modules/jest-jasmine2/build/expectationResultFactory.js:30:20)
      at ctx._transport.flush (../../node_modules/nats-hemera/lib/onClose.js:43:9)
      at Client.Object.<anonymous>.Client.processInbound (../../node_modules/nats/lib/nats.js:805:19)
      at Socket.<anonymous> (../../node_modules/nats/lib/nats.js:470:12)
      at emitOne (events.js:115:13)
      at Socket.emit (events.js:210:7)

  hemera-testPlugin
    ✕ Should be able to add two numbers (2260ms)
```

**Comment by veeramarni** [comment]
Current node version, which i'm using is 8.4.0

**Comment by StarpTech** [comment]
What happens if you remove the `onServerPreRequest` extension?

**Comment by StarpTech** [comment]
Please try a very basic [example](https://github.com/hemerajs/hemera/blob/master/examples/basic/full-example.js) without async await to test if the server starts correctly.

**Comment by veeramarni** [comment]
still, fails after removing it.

**Comment by veeramarni** [comment]
Sorry, this was the same issue I had before. I need to update my `tsconfig.json` file. 

```
{
  "compilerOptions": {
    "target": "es2017",
    "module": "commonjs",
....
}
```
